version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
  my-postgres:
    image: postgres:latest
    environment:
        POSTGRES_DB: "messagesync"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    ports:
        - "5432:5432"  
  generator:
    build:
      context: ./Generator
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      "executor":
        condition: service_started
  executor:
    build:
      context: ./Executor
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      "my-postgres":
        condition: service_started
      "rabbitmq":
        condition: service_healthy